on: 
  push:
    branches: [main]

jobs:
  build_current:
    name: Build current
    runs-on: ubuntu-latest
    container: python:3
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
    - name: Install pre-requisites
      run: pip install -r requirements.txt
    - name: Install mike
      run: pip install mike
    - name: Build
      run: mkdocs build -v --clean
    - name: Configure Git user
      run: |
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         git config --global user.name "github-actions[bot]"
         git config --global --add safe.directory '*'
    - name: Deploy MkDoc with mike 🚀
      run: |
         git fetch origin gh-pages
         git merge origin/gh-pages
         mike deploy --push dev
